//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachment
    {
        public int attachment_id { get; set; }
        public Nullable<int> post_id { get; set; }
        public string file_name { get; set; }
        public virtual post post { get; set; }
    }
}
