//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public int new_id { get; set; }
        public string new_title { get; set; }
        public string new_description { get; set; }
        public Nullable<System.DateTime> new_datebegin { get; set; }
    }
}
