//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class welcome_home
    {
        public int welcome_id { get; set; }
        public string welcome_title { get; set; }
        public string link { get; set; }
        public Nullable<bool> hide { get; set; }
    }
}
